#ifndef __BOSCH_BMA456_DEFS_H__
#define __BOSCH_BMA456_DEFS_H__

//I2C ADDRESS
#define BMA_ADDRESS 0x19

//INTERRUPT CONFIG REGISTERS
#define BMA4_RESERVED_REG_5B_ADDR		UINT8_C(0x5B)
#define BMA4_RESERVED_REG_5C_ADDR		UINT8_C(0x5C)
#define	BMA4_FEATURE_CONFIG_ADDR		UINT8_C(0x5E)
#define	BMA4_CONFIG_STREAM_SIZE		UINT16_C(6144)

//STATUS
#define	BMA4_INTERNAL_ERROR			UINT8_C(0x5F)
#define	BMA4_INTERNAL_STAT			UINT8_C(0x2A)
#define	BMA4_CHIP_ID       			UINT8_C(0x00)

//POWER
#define	BMA4_POWER_CONF_ADDR	UINT8_C(0x7C)
#define	BMA4_POWER_CTRL_ADDR	UINT8_C(0x7D)
#define	BMA4_INIT_CTRL_ADDR			UINT8_C(0x59)

//COMMAND
#define	BMA4_CMD_ADDR		UINT8_C(0X7E)

//ACCELEROMETER CONFIG
#define	BMA4_ACCEL_CONFIG_ADDR		UINT8_C(0X40)
#define	BMA4_ACCEL_RANGE_ADDR		UINT8_C(0X41)

//ACCELEROMETER DATA
#define BMA4_X_AXIS 0x12
#define BMA4_Y_AXIS 0x14
#define BMA4_Z_AXIS 0x16

#endif /*__BOSCH_BMA456_DEFS_H__*/
