#ifndef __BOSCH_BMA456_DEFS_H__
#define __BOSCH_BMA456_DEFS_H__


//INTERRUPT CONFIG REGISTERS
#define BMA4_RESERVED_REG_5B_ADDR		UINT8_C(0x5B)
#define BMA4_RESERVED_REG_5C_ADDR		UINT8_C(0x5C)
#define	BMA4_FEATURE_CONFIG_ADDR		UINT8_C(0x5E)
#define	BMA4_CONFIG_STREAM_SIZE		UINT16_C(6144)

//STATUS
#define	BMA4_INTERNAL_ERROR			UINT8_C(0x5F)
#define	BMA4_INTERNAL_STAT			UINT8_C(0x2A)

//POWER
#define	BMA4_POWER_CONF_ADDR	UINT8_C(0x7C)
#define	BMA4_POWER_CTRL_ADDR	UINT8_C(0x7D)
#define	BMA4_INIT_CTRL_ADDR			UINT8_C(0x59)

#endif /*__BOSCH_BMA456_DEFS_H__*/
